//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TB.Webb.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResumeSection()
        {
            this.ResumeEntry = new HashSet<ResumeEntry>();
        }
    
        public int Id { get; set; }
        public int ResumeId { get; set; }
        public string ContentHeader { get; set; }
        public int Sorter { get; set; }
    
        public virtual Resume Resume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResumeEntry> ResumeEntry { get; set; }
    }
}
