//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TB.Webb.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeContactInfo
    {
        public int Id { get; set; }
        public string Photo { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string WebPage { get; set; }
        public string Github { get; set; }
        public string LinkedIn { get; set; }
        public string ExternalLink1 { get; set; }
        public string ExternalLink2 { get; set; }
        public string ExternalLink3 { get; set; }
    }
}
